baseURL = "https://www.tannersether.com/"
languageCode = "en-us"
title = "Tanner's Site"
theme = "ananke"

# Optional: Add this if you're using the extended version of Hugo
# to support themes with SASS or image processing
enableRobotsTXT = true
[pagination]
  pagerSize = 10


[params]
  description = "A blog about nature, writing, and whatever else comes to mind."

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3
